### ISSUE TITLE
enhancement to single-db vs multi-db page

### ISSUE THREAD

**Issue by macwoody** [babelfish-for-postgresql/babelfish_project_website#101]
After compiling the code, I assume the next step should be provisioning / installing babelfish.
I suggest rename this page to "Installing babelfish" or "Provisioning babelfish" 

And "single-db vs multi-db" should be a subsection of this page. 
Native cross database query processing doesn't exist in PG, it is misleading to describe it expensive.
And I think we don't need to mention MySQL for our purpose.
A more through document is available here: 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish.html

**Comment by 3manuek** [comment]
We can extend the description of the feature by adding [Rob's comment](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/9#issuecomment-963591809) details to the documentation, plus extracting Aurora related documentation.

**Comment by gopinathpai** [comment]
@3manuek - Please assign this to @postgresql007 so he can work directly with @macwoody

**Comment by 3manuek** [comment]
This has been added in #116 .
