### ISSUE TITLE
BABELFISHPG_COMMON: MS SQL DATA TYPES

### ISSUE THREAD

**Issue by macwoody** [babelfish-for-postgresql/babelfish_project_website#102]
In summary, we are providing implementation of T-SQL datatypes. 
I am confused by first paragraph. I am not sure what information we want to deliver through it. 

I suggest that this section to convey following information:
1. purpose of this extension
2. reference to each individual type  link between our datatype and T-SQL document 
( I assume SQL server users can easily what the types are, don't need any description on what the type is )
3. other small issues
3.1 BBF_BINARY is implementation behind sys.BINARY 
3.2 sys.BPCHAR is also an internal type to support NCHAR.

**Comment by gopinathpai** [comment]
@zli236 - Please review @macwoody's comments and provide suggested text to @postgresql007 on how this needs to be updated in the documentation.

**Comment by laurenz** [comment]
@macwoody Could you provide the name of the documentation page this issue refers to?

**Comment by 3manuek** [comment]
I think that the section that @macwoody is referring to is at [_internals/software-architecture.md](https://github.com/babelfish-for-postgresql/babelfish_project_website/blob/main/_internals/software-architecture.md). cc/ @laurenz

**Comment by laurenz** [comment]
@3manuek Thanks, that must be it.

Addressing the pints in the issue:

> I am confused by first paragraph. I am not sure what information we want to deliver through it.

The paragraph is an introduction to the material that follows. It says that the server had to be modified to make Babelfish happen, through outright hacking it up, through hooks and through extensions. I can try to make that somewhat clearer, but details are given in what follows.

> I suggest that this section to convey following information:
>
 > 1.   purpose of this extension

That's stated right there: "Babelfish implements Microsoft SQL Server behavior on top of PostgreSQL"

> 2. reference to each individual type link between our datatype and T-SQL document
>    ( I assume SQL server users can easily what the types are, don't need any description on what the type is )

That is a good idea. I'll try to add that.

> 3. other small issues
>    3.1 BBF_BINARY is implementation behind sys.BINARY
>    3.2 sys.BPCHAR is also an internal type to support NCHAR.

I don't know enough about Babelfish and SQL Server to do that. I'll have to rely on technical input from your side.

**Comment by gopinathpai** [comment]
@macwoody - could you please respond to Laurenz' questions above? Please be as descriptive as possible to provide enough clarity for Laurenz to complete the documentation.

**Comment by laurenz** [comment]
Ok, I have removed the two internal data types from the list.
This is good to go.
