### ISSUE TITLE
BABELFISHPG_MONEY: FIXED PRECISION NUMERIC TYPE

### ISSUE THREAD

**Issue by macwoody** [babelfish-for-postgresql/babelfish_project_website#103]
fixeddecimal is used to implement MONEY type. 
The extension is there to honor the original author. 
Don't need to describe in details how fixeddecimal.

**Comment by gopinathpai** [comment]
@korryd - As discussed please review the documentation and limit it to our changes. For rest of the documentation, we should point to the source at 2nd Quadrant.

**Comment by 3manuek** [comment]
@macwoody Can you please clarify if this is about the website or the extensions repository documentation? If this is related to extensions, I'll move this to the corresponding repo.

**Comment by macwoody** [comment]
it's about website
