### ISSUE TITLE
[Bug]: website points users to wrong repo for bug reports

### ISSUE THREAD

**Issue by nasbyj** [babelfish-for-postgresql/babelfish_project_website#109]
### Contact Details

nasbyj@

### What happened?

https://babelfishpg.org/docs/faq/#how-can-i-report-a-bug points folks at https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/issues, but we should be pointing people to https://github.com/babelfish-for-postgresql/babelfish_extensions/issues

### Version

main (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Fixed at PR #122 .
