### ISSUE TITLE
[Bug]: babelfish_project_website / New Issue has an invalid option

### ISSUE THREAD

**Issue by nasbyj** [babelfish-for-postgresql/babelfish_project_website#110]
### Contact Details

nasbyj@

### What happened?

Among the options presented to users when they hit the New Issue button is "Babelfish for PostgreSQL Website
Please ask and answer questions here.", but that just opens the generic URL for Github communities at large. Until we get discussions setup we should disable that option (and even then I'm thinking we shouldn't have it for the website, only for the extensions repo).

### Version

main (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Fixed at PR #123 .
