### ISSUE TITLE
[Bug]: Collation documentation

### ISSUE THREAD

**Issue by JimFinnerty** [babelfish-for-postgresql/babelfish_project_website#125]
### Contact Details

jfinnert@amazon.com

### What happened?

on this page of the collation documentation:
    https://a4f8b514434154c1af25777bccd0efa0.babelfishpg.org/docs/usage/locales/

1) "Collation ID" in the title should be changed to just "Collation" (or if you prefer "Collation Name", but then you'll also need to change the reference in the prior paragraph to "Collation Name".

2) In the table of collations that may be specified as the server collation name, all of the collations that have "CI_AS" in the name are "nondeterministic", not "deterministic" as it states

3) "also known as CP1252." should end the sentence and then say "CP1 is the abbreviated name for CP1252"

4) all of the statements in the table that talk about "designed for ... <some language>" are somewhat misleading.  This comment refers specifically to the *encoding*.  Use of any of the CPxxx collations is still modified by the default_locale, so a CPxxxx specifier is not language-specific, but the CPxxx specifier controls the single-byte output encoding that will be sent to the client.  The 'designed for' comments have some truth to them, though, because the specific characters that needed by a given language are only available in some encodings.  The focus needs to be that these collations are used to control the client side encoding.

5) "Supports case-insensitive comparison and the LIKE operator." - true, but this is also true of all of the other CI_AS collations in the table, so it implies that the others don't support the LIKE operator.  The collations that don't have CPxxxx in their name, i.e. those that don't specify a code page, use a Unicode client-side encoding.  Those that do have CPxxxx in their name use that code page as the single-byte client side encoding.

6) "You can use the following collations for database objects:" - ALL of the collations can be used for database objects, including the CS_AS form of the collations that were not mentioned in the previous section.  This list of collations is the list of locale-specific collations, which enables a Babelfish application to support more than one locale (otherwise all collations would have the default_locale).

7) "Unicode sorting rules - SQL Server collations sort Unicode-encoded data " ...   That is incorrect, and should be changed to "In SQL Server, "SQL" collations (those that start with the letters "SQL_") sort Unicode-encoded data " ...

8) "however, the order of punctuation and other special characters is different." - however, within the set of punctuation or special characters, the order may be different than it is in the corresponding collation in SQL Server.

9) "As a workaround, we recommend you modify applications that use the SQL_Latin1_General_Pref_CP1_CI_AS collation to use the BBF_SQL_Latin1_General_CP1_CI_AS collation first" - let's change this to suggest using a separate collation for grouping than for ordering.

10) "PostgreSQL uses a specific version of ICU and can match at most one

version of a collation. Variations across versions are unavoidable, as are minor variations across time as languages evolve."

that should have a title such as "PostgreSQL supports exactly one version of each collation          PostgreSQL supports exactly one version of each collation, whereas SQL Server can support multiple versions of the same collation, typically by modifying the collation name with a version suffix such as _80 or _100.

11) "then a AI collation"  - then an AI collation

### Version

main (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gopinathpai** [comment]
@postgresql007 
STEP 1: Was the AWS content from Susan brought into the Open Source documentation? If not, that needs to happen.
STEP 2: Review the above 11 changes requested. Are these changes already in AWS documentation? Add them to Open Source documentation if they are not in AWS documentation
STEP 3: Inform Susan to update AWS documentation if the above 11 comments are missing in AWS documentation.

**Comment by JimFinnerty** [comment]
To attempt to clarify point 4, about code pages:
- Some of the collations have CPxxxx in their name.  In these cases, xxxx is the code page.
- The code page does not specify the locale of the collation, but it does specify a specific single-byte encoding.
- Since each single-byte code page can encode at most 256 characters, this limits what characters can be represented
- Code pages have been designed so that the characters needed by a given region can be represented in a single byte.  A region is not as specific as a locale, but for example it might represent characters typically needed in 'Eastern Europe'
-  The default_locale is still applied to code-page specific collations.  If you use a code page for Eastern Europe, you need to use a compatible default_locale.  It wouldn't make sense to use a Chinese locale with an Eastern European code page, because very few Chinese characters could be represented in such an encoding.
- The code page defines the client encoding.  Collated strings are automatically and transparently translated between the client encoding and the server encoding when data is transmitted between the client and server.

thank you

**Comment by laurenz** [comment]
Thanks.

I have looked over the page with the attempt to incorporate changes from [the Aurora documentation](https://github.com/awsdocs/amazon-aurora-user-guide/blob/main/doc_source/Appendix.SQLServer.CommonDBATasks.Collation.md), but `git blame` tells me there have been none for more than a year.

Also, it seems like the Aurora documentation does not apply; it talks about &ldquo;changing the collation on the database level&rdquo; without telling how to do that &ndash; presumably it is done through a GUI.

Reading the Babelfish page closer, it talks about &ldquo;server collation&rdquo;.
But how do you set a server collation? During `initdb`, right?
So I tried some of these collations with `initdb`, but got the message I'd expect from PostgreSQL:

```none
$ initdb -E UTF8 --locale=BBF_Unicode_General_CI_AS -U postgres x
The files belonging to this database system will be owned by user "laurenz".
This user must also own the server process.

initdb: error: invalid locale name "BBF_Unicode_General_CI_AS"
```

Also, there is no collation on the table level:

```none
1> CREATE DATABASE newdb COLLATE "BBF_Unicode_General_CI_AS";
2> go
Msg 33557097 (severity 16, state 1) from BABELFISH Line 1:
	"'COLLATE' is not currently supported in Babelfish"
```

So, what is it about these collations? As far as I can see, you can only set them on the column level.

I need some input here.

**Comment by JimFinnerty** [comment]
The server collation is stored in the GUC named babelfishpg_tsql.server_collation_name.  The intention is that this is set at Babelfish provisioning time.  It should not be modified after provisioning time.  The default server collation in SQL Server is analogous to the default cluster collation in PostgreSQL.  It is not specified at initdb time, and in fact the Postgres cluster-level collation is also present, and as of PG13 it is always a deterministic libc collation.  In the current release the default server collation must be a case-insensitive, accent-sensitive collation, and it must be an ICU collation. 

The term "locale" is cause for some confusion.  The _locale_ is a property of a collation, and is usually specified with a language code followed by a country code, such as "en_US" or "fr_FR".  In a few cases it can also include additional information such as "es_TRADITIONAL" for traditional Spanish.  This information is stored in the GUC named babelfishpg_tsql.default_locale.  Other properties of interest are whether the collation is case-insensitive or accent-sensitive.  In SQL Server, these properties as well as the code page of the client encoding and the version number of the collation are encoded into the name of the collation.  (SQL Server does not yet support CREATE COLLATION like PostgreSQL does, at the time of this writing).  So you specify all the options you want by selecting the predefined collation that has the properties you want.  In Babelfish, we add the default_locale to the other properties indicated by the name of the collation.  The BBF_Unicode_General_CI_AS doesn't specify a particular locale so this collation will be created at provisioning time by adding the default_locale to its other properties, which in this case are that it is case-insensitive and accent-sensitive, and is not associated with a particular code page, and hence will use a Unicode encoding on the client.  

In the example above the error is raised because at initdb time, the Babelfish extension hasn't been loaded yet, and so the BBF_Unicode_General_CI_AS collation does not yet exist.

Babelfish currently requires the default database collation to be the same as the default server collation (the babelfishpg_tsql.server_collation_name), and the server collation name is specified only at Babelfish provisioning time.

In addition to the server_collation_name, which applies to both the server and database level, you can also set collations at the column level or at the expression level.

**Comment by laurenz** [comment]
Thanks, it is much clearer now:

- The name of the SQL Server collation (unless it is `BBF_Unicode_General_CI_AS`) determines the locale, which is stored in `babelfishpg_tsql.default_locale` when you initialize Babelfish.
- You cannot set a collation for a database or table.

Correct?

Some questions remain:

- If I don't set `babelfishpg_tsql.server_collation_name`, which collation and locale will be chosen?
- If I choose `BBF_Unicode_General_CI_AS`, how will the locale be determined? From the PostgreSQL cluster or database locale?
- Do I get that right that the `babelfishpg_tsql.server_collation_name` determines the TDS client encoding?

**Comment by gopinathpai** [comment]
@JimFinnerty - could you please answer the questions above?
