### ISSUE TITLE
[Update Needed]: Remove the excessive MS SQL Server references

### ISSUE THREAD

**Issue by gopinathpai** [babelfish-for-postgresql/babelfish_project_website#135]
### What happened?

The documentation has several references to MS SQL references. Please remove the ones that are not necessary. 

### Version

main (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laurenz** [comment]
@renee2468 is working on this - see branch "issue-135-replace-MS-SQL".
