### ISSUE TITLE
I don't think we need the word 'standard', and we shouldn't be referencing Sybase (since this project has nothing to do with Sybase):

### ISSUE THREAD

**Issue by susanmdouglas-aws** [babelfish-for-postgresql/babelfish_project_website#140]
I don't think we need the word 'standard', and we shouldn't be referencing Sybase (since this project has nothing to do with Sybase):

As when using Microsoft SQL Server, don't forget to use the <code>GO</code> command after entering one or more SQL statements to instruct Babelfish to execute your commands.

_Originally posted by @susanmdouglas-aws in https://github.com/babelfish-for-postgresql/babelfish_project_website/pull/139#r757407119_

**Comment by renee2468** [comment]
This issue was resolved by PR #141
