### ISSUE TITLE
Determine How to Organize Build Instructions

### ISSUE THREAD

**Issue by slightst** [babelfish-for-postgresql/babelfish_project_website#144]
We have a large number of build tools related to scripts (ex: shell build scripts, CloudFormation). This issue is to discuss, document and finalize the plan.

**Comment by slightst** [comment]
### New repository structure
**[
babelfish_compass](https://github.com/babelfish-for-postgresql/babelfish_compass)**: Existing. Contains build scripts for only 3 flavours: CentOS, Ubuntu, AL2
**babelfish_project**: (new) Contains unrelated tools used that do not belong in the main repo. For example, the plagiarism checker; the script for leaked internal references. 
**babelfish_distributions**: (new) This report contains the binary builds and docker containers, Cloud Formation scripts.


### Decision on builds to support
Build scripts will be provided for the recent LTS of Ubuntu, CentOS and AL2.

**Comment by susanmdouglas-aws** [comment]
@3manuek @slightst  Have we resolved the problems discussed in this issue?  If so, can we close this please?

The installations page:  https://babelfishpg.org/docs/installation/compiling-babelfish-from-source/ now directs the user to see the INSTALLING.md content distributed with the tarball/archive that contains the associated source.  I think that we have the repos in order as well...

**Comment by susanmdouglas-aws** [comment]
I have confirmation from Simon that he thinks we've handled the issue and can close this ticket...
