### ISSUE TITLE
I see that this has been pushed, but there is a typo in the above line... PostgreSQL is misspelled.

### ISSUE THREAD

**Issue by susanmdouglas-aws** [babelfish-for-postgresql/babelfish_project_website#146]
I see that this has been pushed, but there is a typo in the above line... PostgreSQL is misspelled.

_Originally posted by @susanmdouglas-aws in https://github.com/babelfish-for-postgresql/babelfish_project_website/pull/145#r766576912_

**Comment by 3manuek** [comment]
@susanmdouglas-aws I fixed the misspelling in the [issue_99 branch](https://github.com/babelfish-for-postgresql/babelfish_project_website/pull/145/commits/d6ef975eeca30403245ee37cb8299e18e54c51e4) // cc @gopinathpai.

**Comment by 3manuek** [comment]
@susanmdouglas-aws I'm closing this issue as this misspelling has been fixed in the issue_99 branch.
