### ISSUE TITLE
[Documentation]: Minor changes to the collation doc section

### ISSUE THREAD

**Issue by JimFinnerty** [babelfish-for-postgresql/babelfish_project_website#148]
### Contact Details

jfinnert@amazon.com

### What happened?

Two very minor comments (the rest looks good):

the text "For column definitions, you can also use case insensitive or accent sensitive versions"
you meant to say "accent insensitive" instead of "accent sensitive".

Also, in the section heading "Character(SC) expansion", I'm not sure what (SC) means here and I think it should just be deleted. 

-------------

there is a third comment that is correct but I'm wondering if it should be removed:

bin | BIN  requests data to be sorted in code point order, treating the first  character as a wchar. Code point order is a fast deterministic  collation.

Note that we don't include other options in this table that we do not currently support, such as _WS or _VSS or _SC.  Well, we don't support _BIN2 either, and the reason why is that the first character is encoded as a wchar, NOT in the server encoding of UTF8.  So with _BIN2, the first character is encoded _differently_ from the rest of the string, and so the comment that it is sorted in code point order seems not quite correct, since the first character is not a Unicode code point.

In any case, we don't support it, just like we don't support _SC collations etc. either, which are not in this table.  I think bin2 should be removed from this table for consistency.

### Version

main (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laurenz** [comment]
I have fixed the first two points.

I am not sure about the third.

`_bin2` collations are supported in the code; I reverse engineered it.  But I can still remove the reference.

These two uncertainties remain for me:
- should I remove only `_bin` from the text or also the `_bin2` collations?
- There is a whole section dealing with "`bin` and `bin2` that says that `bbf_latin1_general_bin2` is supported. Should that chapter go as well?
