### ISSUE TITLE
[Enhancement]: Restructure Installation steps page 

### ISSUE THREAD

**Issue by 3manuek** [babelfish-for-postgresql/babelfish_project_website#149]
### Contact Details

emanuel@ongres.com

### What this feature/enhancement tries to solve?

For the sake of clarity in the [compiling from source page](https://babelfishpg.org/docs/installation/compiling-babelfish-from-source/), it might be better to mention the [installation scripts](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/50) to make the user go through the installation. 

This page could include extra information, such as pending work on improving the process, environment limitations, etc.

Also, we should split the [single vs multi db page](https://a4f8b514434154c1af25777bccd0efa0.babelfishpg.org/docs/installation/single-multiple/), as it includes some steps that are part of the installation process. The explanation around the Single vs. Multi should be inside the "Using Babelfish" section, and a reference to this page could be mentioned on the installation page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by susanmdouglas-aws** [comment]
@3manuek Has this issue been resolved by the latest update to:  https://babelfishpg.org/docs/installation/compiling-babelfish-from-source/ and if so, can we close this issue?
