### ISSUE TITLE
Setup Forum for Babelfish

### ISSUE THREAD

**Issue by 3manuek** [babelfish-for-postgresql/babelfish_project_website#21]
## Details

Recommended tooling for the purpose: https://github.com/discourse/discourse

Reference: https://discuss.opendistrocommunity.dev/

This may need parking and additional domain allocation different from the website.

**Comment by nasbyj** [comment]
Note that we should set this up in https://github.com/babelfish-for-postgresql/babelfish_extensions, not in this repo.

**Comment by nasbyj** [comment]
@gopinathpai, we discussed this in standup and feel we can hold off on this for now. Do you agree?

**Comment by 3manuek** [comment]
@susanmdouglas-aws even tho we still had not setup the forum, can we close this considering that it is in process of being enabled?

**Comment by susanmdouglas-aws** [comment]
This task will be passed along to the new TPM (when they join us)... we can leave it for now.
