### ISSUE TITLE
[Bug]: Wrong connection behaviour documented for tds_ssl_encrypt

### ISSUE THREAD

**Issue by kuntalghosh** [babelfish-for-postgresql/babelfish_project_website#248]
### Describe the bug

The [documentation](https://babelfishpg.org/docs/usage/security/#handling-ssl-for-client-connections) for different connection scenario w.r.t tds_ssl_encrypt is wrong. It should be same as https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-configuration.html#babelfish-ssl.

Also, the value of the parameter should be true or false instead of 1 or 0.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by susanmdouglas-aws** [comment]
Kuntal, I've just checked in an update to this page:  https://babelfishpg.org/docs/usage/security

Can you verify the fix and close this issue when the fix deploys?  The fix is deploying now...
