### ISSUE TITLE
[Bug]: limitations, Insert: OUTPUT OUTPUT

### ISSUE THREAD

**Issue by dustin-rcg** [babelfish-for-postgresql/babelfish_project_website#249]
### Describe the bug

<img width="944" alt="Screen Shot 2022-12-07 at 1 33 30 PM" src="https://user-images.githubusercontent.com/12749340/206267074-3e457ddb-4157-4ea0-b9d2-d63687a879f4.png">

This seems like a typo. Should it say `OUTPUT INTO`? 
Plain `OUTPUT` seems like it may be implemented because it is similar to `RETURNING` in PG.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by susanmdouglas-aws** [comment]
Hi, it turns out that OUTPUT OUTPUT is a valid (though undocumented clause).  I have updated the docs to note that the inclusion is intentional.  Thank you for your feedback!
