### ISSUE TITLE
"Databases vs. schemas" is inaccurate

### ISSUE THREAD

**Issue by omolenkamp** [babelfish-for-postgresql/babelfish_project_website#66]
https://babelfishpg.org/docs/internals/software-architecture/ says:

> **Databases vs. schemas**
> PostgreSQL offers the following logical structuring of objects inside the database:
> 
> Instance: “one running PostgreSQL”
> Databases: That is what a user connects to
> Schemas: A logical grouping of tables and functions inside a database
> Tables: Where the data is really stored
>
> MS SQL does not have all these layers. The USE command allows us to easily switch between “databases” in MS SQL. However, in contrast to PostgreSQL, it is easily possible to join and switch between these types of databases.

SQL Server does in fact have all of these layers, including [instances](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/database-engine-instances-sql-server) and [schemas](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/ownership-and-user-schema-separation), and they represent the same concepts as they do in PostgreSQL.

Support for cross-database queries is simply a feature that PostgreSQL doesn't have and SQL Server does, it's not the result of different conceptual choices.

**Comment by korryd** [comment]
Thanks for the report, we are looking into this now.

**Comment by 3manuek** [comment]
This is related partially related to [extensions issue #9 ](https://github.com/babelfish-for-postgresql/babelfish_extensions/issues/9), so we'll update this once we get the `contrib/README.md` with the changes.
