### ISSUE TITLE
Installation Steps for Setup

### ISSUE THREAD

**Issue by okeuday** [babelfish-for-postgresql/babelfish_project_website#91]
When going through the installation, there is a gap between https://babelfishpg.org/docs/installation/compiling-babelfish-from-source/ and https://babelfishpg.org/docs/installation/single-multiple/ .  The general information that isn't present is partially present at https://www.postgresql.org/docs/devel/installation.html .  It would be helpful to have an example with Babelfish details to ensure the setup is simple.  My example is from an installation using Ubuntu 20.04:
```shell
sudo adduser postgres
sudo passwd -l postgres
sudo mkdir $INSTALLATION_PATH/data
sudo chown postgres $INSTALLATION_PATH/data
sudo mkdir -p $INSTALLATION_PATH/var/log/postgresql
sudo chown postgres $INSTALLATION_PATH/var/log/postgresql
sudo -Hu postgres /bin/sh
cd $INSTALLATION_PATH/var/log/postgresql
$INSTALLATION_PATH/bin/initdb -D $INSTALLATION_PATH/data

# edit $INSTALLATION_PATH/data/postgresql.conf
# to add the Babelfish extensions preload:
# shared_preload_libraries = 'babelfishpg_tds'

# edit $INSTALLATION_PATH/data/pg_hba.conf
# if it is necessary to add remote Babelfish connection
# access with the md5 METHOD

$INSTALLATION_PATH/bin/pg_ctl -D $INSTALLATION_PATH/data -l postgresql-main.log start
```

**Comment by Toyonut** [comment]
I second this. I have been getting Babelfish running in Docker  for testing here https://github.com/Toyonut/babelfish-testbed. It was only through chance finding decently verbose errors while running the provided SQL in the single-multiple step that I figured out how to get things working. 

This either needs it's own setup page or to be included in the installation page.

**Comment by Toyonut** [comment]
Nice, looks like https://github.com/babelfish-for-postgresql/babelfish_project_website/pull/83 has been updated to cover this now.
