### ISSUE TITLE
Improve the documentation of SSL support for TDS connections

### ISSUE THREAD

**Issue by kuntalghosh** [babelfish-for-postgresql/babelfish_project_website#99]
Currently, there is no documentation for $subject. Here are my thoughts for the initial draft.

1. With SSL support compiled in, the PostgreSQL server needs to be started with SSL enabled by setting the parameter ssl to on in postgresql.conf. Otherwise, SSL support can't be enabled. In case, any client requests for SSL connection, server will reject the connection.
2. TDS extension uses the same OpenSSL configrations as psql connections.
3. There are different options to initiate a SSL connection from a SQL Server client driver. Based on the option, Babelfish server behaves differently. This link documents the current behavior - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-configuration.html#babelfish-ssl.

**Comment by 3manuek** [comment]
Please @kuntalghosh let us know when you'll have completed this.
